'use client'
import Head from "next/head";
import { Col, Row } from "reactstrap";

// --- FIXED IMPORT PATHS ---
// Using '@/' ensures it looks in the 'src' folder correctly
import ProfitChart from "@/app/HeroSection/ProfitChart"; 
import SalesChart from "@/app/(DashboardLayout)/components/dashboard/SalesChart";
import ProjectTables from "@/app/(DashboardLayout)/components/dashboard/ProjectTable";
import TopCards from "@/app/(DashboardLayout)/components/dashboard/TopCards";
import Blog from "@/app/(DashboardLayout)/components/dashboard/Blog";

// --- FIXED IMAGE PATHS ---
// Assuming public folder structure, direct imports usually work from root or public
// If these are in public/images/bg, use string paths in Next/Image component, 
// but if you are importing them as objects, make sure this path is correct relative to src
import bg1 from "public/images/bg/bg1.jpg";
import bg2 from "public/images/bg/bg2.jpg";
import bg3 from "public/images/bg/bg3.jpg";
import bg4 from "public/images/bg/bg4.jpg";

// --- 1. Stats Data (Lawstick Theme) ---
const statsData = [
  { title: "Total Attorney", count: "6", icon: "bi bi-people-fill" },
  { title: "Total Clients", count: "51", icon: "bi bi-people" },
  { title: "Total Cases", count: "9", icon: "bi bi-briefcase-fill" },
  { title: "Ongoing Cases", count: "1", icon: "bi bi-journal-text" },
  { title: "Success Cases", count: "2", icon: "bi bi-check-circle-fill" },
  { title: "Wallet", count: "$11133", icon: "bi bi-wallet-fill" },
];

// --- 2. Blog Data ---
const BlogData = [
  {
    image: bg1,
    title: "This is simple blog",
    subtitle: "2 comments, 1 Like",
    description: "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
  {
    image: bg2,
    title: "Lets be simple blog",
    subtitle: "2 comments, 1 Like",
    description: "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
  {
    image: bg3,
    title: "Don't ",
    subtitle: "2 comments, 1 Like",
    description: "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
  {
    image: bg4,
    title: "Simple is beautiful",
    subtitle: "2 comments, 1 Like",
    description: "This is a wider card with supporting text below as a natural lead-in to additional content.",
    btnbg: "primary",
  },
];

export default function Home() {
  return (
    <div>
      <Head>
        <title>Lawstick Admin Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* --- Global CSS for Rounded Cards --- */}
      <style>{`
        .card {
          border-radius: 20px !important;
          border: none !important;
          box-shadow: 0 4px 12px rgba(0,0,0,0.05) !important;
          overflow: hidden;
        }
      `}</style>

      <div>
        
        {/* --- SECTION 1: PROFIT CHART (Top) --- */}
        <Row>
          <Col sm="12">
            <ProfitChart />
          </Col>
        </Row>

        {/* --- SECTION 2: TOP CARDS (6 Boxes) --- */}
        <Row>
          {statsData.map((item, index) => (
            <Col sm="6" lg="4" key={index} className="mb-4">
              <TopCards
                bg="bg-light-warning text-warning"
                title=""
                subtitle={item.title}
                earning={item.count}
                icon={item.icon}
              />
            </Col>
          ))}
        </Row>

        {/* --- SECTION 3: SALES CHART (Revenue + Case Analytics) --- */}
        <SalesChart />

        {/* --- SECTION 4: TABLE --- */}
        <Row>
          <Col lg="12" sm="12">
            <ProjectTables />
          </Col>
        </Row>

      </div>
    </div>
  );
}